{
 "title": "Logs especificos",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "NLP_RASA",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"nlp\"}"
    }
   ]
  },
  {
   "title": "Logs ASR",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"asr\"}"
    }
   ]
  },
  {
   "title": "Licencias WebRtc",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"} |~ \"FEATURE_WEBRTC_PORTS\""
    }
   ]
  },
  {
   "title": "Licencias CallDirector1",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/cms.log\",job=\"licencias_caldirector1\"}|~ \"FEATURE_ANNOUNCEMENT_PORTS\""
    }
   ]
  }
 ]
}