{
 "title": "Logs Licencias",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CallDirector_2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Llamadas SIP concurrentes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_sip-connectivity_Components",
     "select": [
      [
       {
        "params": [
         "CurrentNumberOfEstablishedConnections"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "cms2" }
     ]
    }
   ]
  },
  {
   "title": "numeros",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"licencias_cms2\"} |= \"Fire event [RING] to client\""
    }
   ]
  },
  {
   "title": "numeros",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time (    \r\n    {job=\"licencias_cms2\"} |= \"Fire event [RING] to client\" [5s]\r\n)"
    }
   ]
  },
  { "title": "CALL_DIRECTOR_2", "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CallDirector_1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "CALL_DIRECTOR_1",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/cms.log\",job=\"licencias_cms1\"}"
      }
     ]
    },
    {
     "title": "numeros",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum(count_over_time (    \r\n    {job=\"licencias_cms1\"} |= \"Fire event [RING] to client\" [1s]\r\n))"
      }
     ]
    },
    {
     "title": "test",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max (count_over_time({filename=\"/var/log/cms.log\",job=\"licencias_cms1\"} | logfmt |= \"Fire event [RING] to client\" [2m] ))"
      }
     ]
    },
    {
     "title": "Llamadas SIP concurrentes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 50 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "CMS_sip-connectivity_Components",
       "select": [
        [
         {
          "params": [
           "MaxConcurrentConnectionsCurrentHour"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "cms1" }
       ]
      }
     ]
    },
    {
     "title": "Numero de rings",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count_over_time (    \r\n    {job=\"licencias_cms1\"} |= \"Fire event [RING] to client\" [3s]\r\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "WebRTC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "count_over_time({filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"} |= \"INFO\" [1m])"
      }
     ]
    },
    {
     "title": "DEBUG",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 3 },
     "targets": [
      {
       "expr": "count_over_time({filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"} |= \"DEBUG\" [1m])"
      }
     ]
    },
    {
     "title": "INFO",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"} |logfmt |= \"INFO\" [1m]))"
      }
     ]
    },
    {
     "title": "DEBUG",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"} |= \"DEBUG\" [1m] ))"
      }
     ]
    },
    {
     "title": "ERROR",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"} |logfmt |= \"ERROR\" [1m]))"
      }
     ]
    },
    {
     "title": "Logs del servidor WebRTC",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"}"
      }
     ]
    },
    {
     "title": "Licencias consumidas",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_over_time({filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"} |logfmt |~ \"One Feature Ports license for extension.*\" [1m])"
      }
     ]
    },
    {
     "title": "Licencias WebRtc",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"} |~ \"FEATURE_WEBRTC_PORTS\""
      }
     ]
    },
    {
     "title": "Licencias",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "count_over_time({filename=\"/var/log/cms.log\",job=\"licencias_webrtc\"} |~ \"FEATURE_WEBRTC_PORTS:.* Licenses available:.*[2]\" [1m])"
      }
     ]
    }
   ]
  }
 ]
}