{
 "title": "MVP",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sectoriales",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Punto de Entrada",
   "type": "piechart",
   "description": "34931114004 Opcion 1\n34931114005 Opcion 2",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select origen, count(*) AS cuenta FROM temporal GROUP BY origen"
    }
   ]
  },
  {
   "title": "DNI / NIE",
   "type": "piechart",
   "description": "DNI = 1\nNIE = 2",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select dni_nie, count(*) AS valor FROM temporal GROUP BY dni_nie"
    }
   ]
  },
  {
   "title": "Numeros Bloqueados",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "rawSql": "SELECT * from login_attempts" }
   ]
  },
  { "title": "Tablas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MVP",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM temporal\nORDER BY id"
    }
   ]
  }
 ]
}