{
 "title": "OSCC CMS",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "linux",
  "cms",
  "telegraf",
  "jolokia"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host WHERE system_type=~/^CMS$/"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/ and (path !~ /net|vobs|cm|\\/home\\/users|view|cds/)"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   },
   {
    "name": "ncpu",
    "label": "Number of CPU's",
    "query": "SHOW TAG VALUES CARDINALITY FROM \"cpu\" WITH KEY = \"cpu\" WHERE \"cpu\" =~ /cpu\\d/ AND host =~ /$server/"
   },
   {
    "name": "Container",
    "label": "container",
    "query": "show tag values from docker_container_cpu with key=\"container_name\""
   }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CMS Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \"value\" AS \"server\" FROM \"exec\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "ASR / TTS Status",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Description" ], "type": "tag" }
     ],
     "measurement": "CMS_streaming-mps_Components_Sanity",
     "query": "SELECT last(\"Status\") AS \"Status\" FROM \"CMS_streaming-mps_Components_Sanity\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"Description\"",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "SIP Server Status",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Description" ], "type": "tag" }
     ],
     "measurement": "CMS_sip-connectivity_Components_Sanity",
     "query": "SELECT last(\"Status\") AS \"Status\" FROM \"CMS_sip-connectivity_Components_Sanity\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"Description\"",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"usage_iowait\"), 1s) FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  { "title": "CMS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Java Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "CMS - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(\"MaxHeapSizeLimit\") AS \"Heap Size Limit\", mean(\"HeapMemoryUsage.used\") AS \"Heap Used\", mean(\"HeapMemoryUsage.committed\") AS \"Heap Committed\", mean(\"NonHeapMemoryUsage.used\") AS \"NonHeap Used\", mean(\"NonHeapMemoryUsage.committed\") AS \"NonHeap Committed\" FROM \"telegraf\".\"autogen\".\"CMS_java-lang_Memory\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DIALER - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(\"MaxHeapSizeLimit\") AS \"Heap Size Limit\", mean(\"HeapMemoryUsage.used\") AS \"Heap Used\", mean(\"HeapMemoryUsage.committed\") AS \"Heap Committed\", mean(\"NonHeapMemoryUsage.used\") AS \"NonHeap Used\", mean(\"NonHeapMemoryUsage.committed\") AS \"NonHeap Committed\" FROM \"telegraf\".\"autogen\".\"DIALER_java-lang_Memory\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Java Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CMS - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_java-lang_Threading",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "DaemonThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Daemon Count" ], "type": "alias" }
      ],
      [
       { "params": [ "PeakThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Peak Count" ], "type": "alias" }
      ],
      [
       { "params": [ "ThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "DIALER - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DIALER_java-lang_Threading",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "DaemonThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Daemon Count" ], "type": "alias" }
      ],
      [
       { "params": [ "PeakThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Peak Count" ], "type": "alias" }
      ],
      [
       { "params": [ "ThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "SIP Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_sip-connectivity_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       {
        "params": [
         "CurrentNumberOfEstablishedConnections"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Established" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "CurrentNumberOfEstablishingConnections"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Establishing" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "CurrentNumberOfDisconnectingConnections"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disconnecting" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "WebRTC Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_paas-connectivity_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "CurrentNumberOfAllConnections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CurrentCalls" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_turn_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "ActiveUserCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "TURNActive" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "exec",
     "query": "SELECT count(\"Id\") AS \"WebRTCAccounts\" FROM \"exec\" WHERE (\"host\" =~ /^$server$/ AND \"type\" = \"WebRTCaccounts\") AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 2" ], "type": "math" },
       { "params": [ "WebRTCAccounts" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "WebRTCaccounts" }
     ]
    }
   ]
  },
  {
   "title": "IVR Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_AF-Provider_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfSessions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CurrentCalls" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RTP Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfEndpoints" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfAudioRtpStreams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Audio" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfVideoRtpStreams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Video" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfG711Streams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "G711" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfG7221Streams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "G7221" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfG722Streams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "G722" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfG729Streams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "G729" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfOpusStreams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Opus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfH264Streams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "H264" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_streaming-mps_Components",
     "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "NumberOfVp8Streams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Vp8" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\")  / $ncpu) AS \"Java\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'java') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $ncpu" ], "type": "math" },
       { "params": [ "Java" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") / $ncpu) AS \"nativeRTPunit\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'nativeRTPunit-x86_64') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $ncpu" ], "type": "math" },
       { "params": [ "nativeRTPunit" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "nativeRTPunit-x86_64" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\")  / $ncpu) AS \"postgres\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'postgres') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $ncpu" ], "type": "math" },
       { "params": [ "nativeRTPunit" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "postgres" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"cla\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'cla') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cla" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "cla" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"ffmpeg\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'ffmpeg') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cla" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "cla" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"NSSserver\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'NSSserver') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cla" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "cla" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"nuance-server\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'nuance-server') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cla" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "nuance-server" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"dockerd\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'dockerd') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cla" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "nuance-server" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"docker-containerd\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'docker-containerd') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cla" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "nuance-server" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"docker-containerd-shim\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'docker-containerd-shim') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cla" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "nuance-server" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (mean(\"cpu_usage\")  / $ncpu) AS \"Java\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'java') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Java" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "java" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") / $ncpu) AS \"nativeRTPunit\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'nativeRTPunit-x86_64') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "nativeRTPunit" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "nativeRTPunit-x86_64" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\")  / $ncpu) AS \"postgres\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'postgres') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "postgres" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "postgres" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"cla\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'cla') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cla" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "cla" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"ffmpeg\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'ffmpeg') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ffmpeg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "ffmpeg" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"ffmpeg\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'ffmpeg') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "NSSserver" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "NSSserver" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"ffmpeg\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'ffmpeg') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "nuance-server" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "nuance-server" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"ffmpeg\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'ffmpeg') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "dockerd" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "dockerd" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"ffmpeg\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'ffmpeg') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "docker-containerd" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "docker-containerd" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT (max(\"cpu_usage\") /$ncpu) AS \"ffmpeg\" FROM \"procstat\" WHERE (\"host\" =~ /^$server$/ AND \"process_name\" = 'ffmpeg') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "docker-containerd-shim" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "docker-containerd-shim" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CMS - Garbage Collection Count - $tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "CMS_java-lang_garbage_collector",
     "query": "SELECT difference(\"CollectionCount\") AS \"GC Collection Count\" FROM \"tomcat_jvm_garbage_collector\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "DIALER - Garbage Collection Count - $tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "DIALER_java-lang_garbage_collector",
     "query": "SELECT difference(\"CollectionCount\") AS \"GC Collection Count\" FROM \"tomcat_jvm_garbage_collector\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "CMS - Garbage Collection Time - $tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "CMS_java-lang_garbage_collector",
     "query": "SELECT difference(\"CollectionCount\") AS \"GC Collection Count\" FROM \"tomcat_jvm_garbage_collector\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "CollectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "DIALER - Garbage Collection Time - $tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "DIALER_java-lang_garbage_collector",
     "query": "SELECT difference(\"CollectionCount\") AS \"GC Collection Count\" FROM \"tomcat_jvm_garbage_collector\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "CollectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Query",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         "Number of transactions committed"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "xact_rollback" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         "Number of transactions rollbacked"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "tup_inserted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Number of rows inserted" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Number of rows deleted" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_updated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Number of rows updated" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Number of buffers allocated" ], "type": "alias" }
      ],
      [
       { "params": [ "buffers_backend" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "Number of buffers written directly by a backend"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Conflicts / Deadlocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Conflicts",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Deadlocks",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_connections",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "state", "operator": "=", "value": "active" }
     ]
    },
    {
     "alias": "Idle",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_connections",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "state", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_schemas_size",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cms-recorder" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "schema_name", "operator": "=", "value": "cms-recorder" }
     ]
    },
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_schemas_size",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "postgres" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "schema_name", "operator": "=", "value": "postgres" }
     ]
    },
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_schemas_size",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cms-dialer" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "schema_name", "operator": "=", "value": "cms-dialer" }
     ]
    }
   ]
  },
  {
   "title": "Recorder DB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CMS_DB",
     "query": "SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "recorded" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Recorded" ], "type": "alias" }
      ],
      [
       { "params": [ "cti" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Recorded with CTI" ], "type": "alias" }
      ],
      [
       { "params": [ "erased" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Deleted" ], "type": "alias" }
      ],
      [
       { "params": [ "erasedwithbackup" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Deleted with backuped" ], "type": "alias" }
      ],
      [
       { "params": [ "erasedwithoutbackup" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Deleted without backuped" ], "type": "alias" }
      ],
      [
       { "params": [ "backuped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Backuped" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Dialer DB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col $tag_dialerstate",
     "function": "mean",
     "groupBy": [
      { "params": [ "dialerstate" ], "type": "tag" }
     ],
     "measurement": "CMS_DB_Dialer",
     "query": "SELECT \"dialerstatevalue\" AS \"Campaign State\" FROM \"CMS_DB\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"dialerstate\"",
     "select": [
      [
       { "params": [ "dialerstatevalue" ], "type": "field" },
       { "params": [ "Campaign State" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col $tag_dialercallresult",
     "function": "mean",
     "groupBy": [
      { "params": [ "dialercallresult" ], "type": "tag" }
     ],
     "measurement": "CMS_DB_Dialer",
     "query": "SELECT \"dialerstatevalue\" AS \"Campaign State\" FROM \"CMS_DB\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"dialerstate\"",
     "select": [
      [
       { "params": [ "dialercallresultvalue" ], "type": "field" },
       { "params": [ "Call results" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Container: $Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "repeat": "Container",
   "collapsed": true,
   "panels": [
    {
     "title": "Resource usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$Container: cpu",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_cpu\" WHERE (\"container_name\" =~ /^$Container$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / $ncpu" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$Container: memory",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "query": "SELECT mean(usage_in_usermode) as \"usermode\", mean(usage_system) as \"system\", mean(usage_in_kernelmode) as \"kernelmode\" FROM \"docker_container_cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "alias": "$Container: read",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "query": "SELECT mean(usage_in_usermode) as \"usermode\", mean(usage_system) as \"system\", mean(usage_in_kernelmode) as \"kernelmode\" FROM \"docker_container_cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_read"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$Container: write",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "query": "SELECT mean(usage_in_usermode) as \"usermode\", mean(usage_system) as \"system\", mean(usage_in_kernelmode) as \"kernelmode\" FROM \"docker_container_cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_write"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Load averages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "system_load1",
       "query": "SELECT mean(load1) as short,mean(load5) as medium,mean(load15) as long FROM \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT mean(running) as running, mean(blocked) as blocked, mean(sleeping) as sleeping, mean(stopped) as stopped, mean(zombies) as zombies, mean(paging) as paging, mean(unknown) as unknown FROM \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Forks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 120 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT non_negative_derivative(mean(processes_forked),1s) as forks FROM \"kernel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(\"file-max\") as max FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(\"file-nr\") as opened FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "File Descriptors per process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_process_name ($tag_pid)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "process_name" ], "type": "tag" },
        { "params": [ "pid" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "num_fds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Threads per process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_process_name ($tag_pid)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "process_name" ], "type": "tag" },
        { "params": [ "pid" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "num_threads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interrupts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_irq",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "irq" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "interrupts",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Per-cpu usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage for $cpu",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
     "repeat": "cpu",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $cpu $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netfilter conntrack usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 176 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$server: current",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "conntrack",
       "select": [
        [
         { "params": [ "ip_conntrack_count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$server: maximum",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "conntrack",
       "select": [
        [
         { "params": [ "ip_conntrack_max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network stack (TCP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 177 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT mean(tcp_close) as CLOSED, mean(tcp_close_wait) as CLOSE_WAIT, mean(tcp_closing) as CLOSING, mean(tcp_established) as ESTABLISHED, mean(tcp_fin_wait1) as FIN_WAIT1, mean(tcp_fin_wait2) as FIN_WAIT2, mean(tcp_last_ack) as LAST_ACK, mean(tcp_syn_recv) as SYN_RECV, mean(tcp_syn_sent) as SYN_SENT, mean(tcp_time_wait) as TIME_WAIT FROM \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TCP aborts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 184 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "on close",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnClose" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "on data",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnData" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "timeout",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnTimeout" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "failed",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortFailed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "linger",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnLinger" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "memory",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnMemory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP handshake issues",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 191 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "estabresets",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "outrsts",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(tcp_outrsts), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "activeopens",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(tcp_activeopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "passiveopens",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(tcp_passiveopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP SYN cookies",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 198 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "failed",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtSyncookiesFailed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "received",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtSyncookiesRecv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "sent",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtSyncookiesSent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 198 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "in echos",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInEchos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out echos",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpOutEchos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in echo responses",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInEchoReps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out echo responses",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpOutEchoReps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 198 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "in errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpOutErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "checksum errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInCsumErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "IPv4 errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 205 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "in discards",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out discards",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpOutDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in hdr errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInHdrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in addr errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInAddrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out no routes",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpOutNoRoutes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in unknown protocol",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInUnknownProtos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "IPv6 errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 205 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "in discards",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out discards",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6OutDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in hdr errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InHdrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in addr errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InAddrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out no routes",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6OutNoRoutes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in unknown protocol",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InUnknownProtos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network stack (UDP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDP datagrams",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 178 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(udp_indatagrams), 1s) as \"in datagrams\" FROM \"net\" WHERE host =~ /$server/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(udp_outdatagrams), 1s) as \"out datagrams\" FROM \"net\" WHERE host =~ /$server/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UDP buffer errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 185 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Send buffer errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpSndbufErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Receive buffer errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpRcvbufErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "UDP errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 185 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "checksum errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpInCsumErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpInErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "no ports",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpNoPorts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "repeat": "netif",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 179 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"in\"  FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 179 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network drops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 186 },
     "yaxes": [
      { "format": "pps", "label": "Drops per second" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(drop_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(drop_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 186 },
     "yaxes": [
      { "format": "short", "label": "Errors per second" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(err_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(err_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap I/O bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 180 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT non_negative_derivative(mean(\"in\")) as \"in\", non_negative_derivative(mean(\"out\")) as \"out\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 180 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT mean(used) as \"used\"  FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS for /dev/$disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O requests for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 138 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 138 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O time for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 138 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "repeat": "mountpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 190 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_total",
       "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" =~ /^$mountpoint$/AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 190 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics velocity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delivery time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 192 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "Delivery time",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_write",
       "select": [
        [
         { "params": [ "write_time_ns" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Gather time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 192 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "Gather time",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_gather",
       "select": [
        [
         { "params": [ "gather_time_ns" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Written metrics",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 192 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Metrics written",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_agent",
       "select": [
        [
         { "params": [ "metrics_written" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 192 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Gather errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_agent",
       "select": [
        [
         { "params": [ "gather_errors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Dropped metrics",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_agent",
       "select": [
        [
         { "params": [ "metrics_dropped" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}