{
 "title": "OSCC Application Servers",
 "description": "OSCC metrics Dashboard using telegraf",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_TELEGRAF", "label": "Database", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM win_system WITH KEY=host WHERE system_type=~ /^oscc-application-server$/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM win_cpu WITH KEY = \"DPC Rate\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM win_physdisk WITH KEY=instance WHERE host =~ /$server/"
   },
   {
    "name": "adapter",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM win_net WITH KEY=instance WHERE host =~ /$server/"
   },
   {
    "name": "ncpu",
    "label": "Number of CPU's",
    "query": "SELECT \"n_cpus\" FROM \"system\" WHERE host =~ /$server/"
   },
   {
    "name": "Tomcat_connector",
    "label": "Connector",
    "query": "SHOW TAG VALUES FROM \"tomcat_ThreadPool\" WITH KEY = \"name\" WHERE system_type=~ /^oscc-application-server$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Application Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "softwareVersion",
     "query": "SELECT \"value\" AS \"application\" FROM \"softwareVersion\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_Server",
     "query": "SELECT \"serverInfo\" AS \"Version\" FROM \"tomcat_Server\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "serverInfo" ], "type": "field" },
       { "params": [ "Version" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "select": [
      [
       { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Percent_Committed_Bytes_In_Use" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_swap",
     "select": [
      [
       { "params": [ "Percent_Usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "_Total" }
     ]
    }
   ]
  },
  {
   "title": "Drive C: used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "C:" }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "Processes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "DPC_Rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "Processor_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "OSCC Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "OSCC Application Server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_process",
       "query": "SELECT (mean(\"Percent_Processor_Time\")/$ncpu) FROM \"win_process\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" =~ /^tomcat/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=", "value": "tomcat8" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "OSCC Application Server (Total Memory Usage)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_process",
       "query": "SELECT mean(\"Private_Bytes\") FROM \"win_process\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" =~ /^tomcat/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "Private_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^tomcat/" }
       ]
      },
      {
       "alias": "OSCC Application Server (Ram Usage)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_process",
       "query": "SELECT mean(\"Working_Set_-_Private\") FROM \"win_process\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" =~ /^tomcat/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "Working_Set_-_Private" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^tomcat/" }
       ]
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "OSCC Application Server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_process",
       "query": "SELECT mean(\"IO_Read_Bytes_persec\") FROM \"win_process\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" =~ /^tomcat/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "IO_Read_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^tomcat/" }
       ]
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "OSCC Application Server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_process",
       "query": "SELECT mean(\"IO_Write_Bytes_persec\") FROM \"win_process\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" =~ /^tomcat/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "IO_Write_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^tomcat/" }
       ]
      }
     ]
    },
    {
     "title": "Handle Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "OSCC Application Server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_process",
       "query": "SELECT mean(\"Handle_Count\") FROM \"win_process\" WHERE (\"host\" =~ /^$server$/ AND \"instance\" =~ /^tomcat/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "Handle_Count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^tomcat/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Java",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Java",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_jvm_memory",
       "query": "SELECT mean(\"HeapMemoryUsage.max\") AS \"Heap Size Limit\", mean(\"HeapMemoryUsage.used\") AS \"Heap Used\", mean(\"HeapMemoryUsage.committed\") AS \"Heap Committed\", mean(\"NonHeapMemoryUsage.used\") AS \"NonHeap Used\", mean(\"NonHeapMemoryUsage.committed\") AS \"NonHeap Committed\" FROM \"tomcat_jvm_memory\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Heap Size Limit" ], "type": "alias" }
        ],
        [
         { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Heap Used" ], "type": "alias" }
        ],
        [
         { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Heap Committed" ], "type": "alias" }
        ],
        [
         { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "NonHeap Used" ], "type": "alias" }
        ],
        [
         { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "NonHeap Committed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Java Threads",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_jvm_lang_Threading",
       "query": "SELECT mean(\"DaemonThreadCount\") AS \"Daemon Count\", mean(\"PeakThreadCount\") AS \"Peak Count\", mean(\"ThreadCount\") AS \"Count\" FROM \"CMS_java-lang_Threading\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) ",
       "select": [
        [
         { "params": [ "DaemonThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Daemon Count" ], "type": "alias" }
        ],
        [
         { "params": [ "PeakThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Peak Count" ], "type": "alias" }
        ],
        [
         { "params": [ "ThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connector Network",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "tomcat_GlobalRequestProcessor",
       "query": "SELECT difference(\"bytesReceived\") AS \"Bytes Received\", difference(\"bytesSent\") AS \"Bytes Sent\" FROM \"tomcat_GlobalRequestProcessor\" WHERE (\"host\" =~ /^$server$/ AND \"name\" =~ /^$Tomcat_connector$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "bytesReceived" ], "type": "field" },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "Bytes Received" ], "type": "alias" }
        ],
        [
         { "params": [ "bytesSent" ], "type": "field" },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "Bytes Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tomcat_connector$/" }
       ]
      }
     ]
    },
    {
     "title": "Connector Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "alias": "$col - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "tomcat_GlobalRequestProcessor",
       "query": "SELECT difference(\"requestCount\") AS \"Request Count\", difference(\"errorCount\") AS \"Error Count\" FROM \"tomcat_GlobalRequestProcessor\" WHERE (\"host\" =~ /^$server$/ AND \"name\" =~ /^$Tomcat_connector$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "requestCount" ], "type": "field" },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "Request Count" ], "type": "alias" }
        ],
        [
         { "params": [ "errorCount" ], "type": "field" },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "Error Count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tomcat_connector$/" }
       ]
      }
     ]
    },
    {
     "title": "Connector Processing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$col - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "tomcat_GlobalRequestProcessor",
       "query": "SELECT difference(\"processingTime\") AS \"Processing Time\" FROM \"tomcat_GlobalRequestProcessor\" WHERE (\"host\" =~ /^$server$/ AND \"name\" =~ /^$Tomcat_connector$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "processingTime" ], "type": "field" },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "Processing Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tomcat_connector$/" }
       ]
      }
     ]
    },
    {
     "title": "Connector Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "tomcat_ThreadPool",
       "query": "SELECT \"maxThreads\" AS \"Max Threads\", \"currentThreadCount\" AS \"Current Threads\", \"currentThreadsBusy\" AS \"Current Threads Busy\" FROM \"tomcat_ThreadPool\" WHERE (\"host\" =~ /^$server$/ AND \"name\" =~ /^$Tomcat_connector$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "maxThreads" ], "type": "field" },
         { "params": [ "Max Threads" ], "type": "alias" }
        ],
        [
         { "params": [ "currentThreadCount" ], "type": "field" },
         { "params": [ "Current Threads" ], "type": "alias" }
        ],
        [
         { "params": [ "currentThreadsBusy" ], "type": "field" },
         { "params": [ "Current Threads Busy" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tomcat_connector$/" }
       ]
      }
     ]
    },
    {
     "title": "Connector Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "tomcat_ThreadPool",
       "query": "SELECT \"connectionCount\" AS \"Connections\" FROM \"tomcat_ThreadPool\" WHERE (\"host\" =~ /^$server$/ AND \"name\" =~ /^$Tomcat_connector$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "connectionCount" ], "type": "field" },
         { "params": [ "Connections" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tomcat_connector$/" }
       ]
      }
     ]
    },
    {
     "title": "Garbage Collection Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Garbage Collection Count - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "tomcat_jvm_garbage_collector",
       "query": "SELECT difference(\"CollectionCount\") FROM \"tomcat_jvm_garbage_collector\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionCount" ], "type": "field" },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Garbage Collection Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Garbage Collection Time - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "tomcat_jvm_garbage_collector",
       "query": "SELECT difference(\"CollectionTime\") FROM \"tomcat_jvm_garbage_collector\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionTime" ], "type": "field" },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Collection Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Collection - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tomcat_jvm_memory_pool",
       "query": "SELECT mean(\"CollectionUsage.committed\") AS \"Commited\", mean(\"CollectionUsage.init\") AS \"Init\", mean(\"CollectionUsage.max\") AS \"Max\", mean(\"PeakUsage.used\") AS \"Used\" FROM \"tomcat_jvm_memory_pool\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(none)",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Commited" ], "type": "alias" }
        ],
        [
         { "params": [ "CollectionUsage.init" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Init" ], "type": "alias" }
        ],
        [
         { "params": [ "CollectionUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "PeakUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Peak Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Peak - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tomcat_jvm_memory_pool",
       "query": "SELECT mean(\"PeakUsage.committed\") AS \"Commited\", mean(\"PeakUsage.init\") AS \"Init\", mean(\"CollectionUsage.max\") AS \"Max\", mean(\"PeakUsage.used\") AS \"Used\" FROM \"tomcat_jvm_memory_pool\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(none)",
       "select": [
        [
         { "params": [ "PeakUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Commited" ], "type": "alias" }
        ],
        [
         { "params": [ "PeakUsage.init" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Init" ], "type": "alias" }
        ],
        [
         { "params": [ "CollectionUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "PeakUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Pool - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tomcat_jvm_memory_pool",
       "query": "SELECT mean(\"Usage.committed\") AS \"Commited\", mean(\"Usage.init\") AS \"Init\", mean(\"Usage.max\") AS \"Max\", mean(\"Usage.max\") AS \"Used\" FROM \"tomcat_jvm_memory_pool\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(none)",
       "select": [
        [
         { "params": [ "Usage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Commited" ], "type": "alias" }
        ],
        [
         { "params": [ "Usage.init" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Init" ], "type": "alias" }
        ],
        [
         { "params": [ "Usage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "Usage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cpu Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "Percent_Processor_time",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" = 'itrivsuswp01' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Physical Memory statistics",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Available Memory",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Pool Non Paged",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Pool_Nonpaged_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "itrivsuswp01" }
       ]
      },
      {
       "alias": "Pool Paged",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Pool_Paged_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "itrivsuswp01" }
       ]
      }
     ]
    },
    {
     "title": "System Paging",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Pages/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Pages_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Pages Read/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Page_Reads_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Pages Write/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Page_Writes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk$disk Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Disk read/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_physdisk",
       "select": [
        [
         { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "Disk write/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_physdisk",
       "select": [
        [
         { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk$disk Latency and Fragmentation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "Disk read latency",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_physdisk",
       "select": [
        [
         { "params": [ "Avg._Disk_sec/Read" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "Disk write latency",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_physdisk",
       "select": [
        [
         { "params": [ "Avg._Disk_sec/Write" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "Disk  split IO/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_physdisk",
       "select": [
        [
         { "params": [ "Split_IO_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk$disk Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Current Disk Queue Length",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_physdisk",
       "select": [
        [
         { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "Average Disk Queue Length",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_physdisk",
       "select": [
        [
         { "params": [ "Avg._Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk$disk I/O",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "alias": "Disk read/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_physdisk",
       "select": [
        [
         { "params": [ "Disk_Reads_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "Disk write/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_physdisk",
       "select": [
        [
         { "params": [ "Disk_Writes_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$adapter Network Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps", "label": "bytes" }
     ],
     "targets": [
      {
       "alias": "Bytes received/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$adapter$/" }
       ]
      },
      {
       "alias": "Bytes sent/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Packets_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$adapter$/" }
       ]
      }
     ]
    },
    {
     "title": "$adapter Network Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "alias": "Packets received/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Packets_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$adapter$/" }
       ]
      },
      {
       "alias": "Packets sent/sec",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Packets_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$adapter$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}