{
 "title": "Recursos_Maquinas (11074)",
 "description": "【English version】Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}))"
    }
   },
   { "name": "tipo", "label": "Tipo_Servidor", "query": { "query": "label_values(tipo)" } },
   {
    "name": "entorno",
    "label": "Ubicacion",
    "query": {
     "query": "label_values(node_uname_info{tipo=~\"$tipo\"}, entorno)"
    }
   },
   {
    "name": "servidor",
    "label": "Servidor",
    "query": {
     "query": "label_values(node_uname_info{entorno=~\"$entorno\"}, servidor)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview ，Host：$servidor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Resource Overview【JOB：$servidor，Visualizando：$total】",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})by(servidor)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mode='system'}) by (servidor)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mode=\"idle\"}[$interval])) by (servidor)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} / (node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{otipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.?|xfs\"})))by(servidor)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])) by (servidor)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])) by (servidor)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])*8) by (servidor)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])*8) by (servidor)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "$job：Overall total 5m load & average CPU used%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Total 5m load" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\", mode='system'})",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "sum(node_load5{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})",
     "legendFormat": "Total 5m load"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mode=\"idle\"}[$interval])) by (servidor)) * 100",
     "legendFormat": "Overall average used%"
    }
   ]
  },
  {
   "title": "$job：Overall total memory & average memory used%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} - node_memory_MemAvailable_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} - node_memory_MemAvailable_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}) / sum(node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}))*100",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  {
   "title": "$job：Overall total disk & average disk used%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"xfs|ext.*\"})by(device,servidor))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"xfs|ext.*\"})by(device,servidor)) - sum(avg(node_filesystem_free_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"xfs|ext.*\"})by(device,servidor))",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"xfs|ext.*\"})by(device,servidor)) - sum(avg(node_filesystem_free_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"xfs|ext.*\"})by(device,servidor))) *100/(sum(avg(node_filesystem_avail_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"xfs|ext.*\"})by(device,servidor))+(sum(avg(node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"xfs|ext.*\"})by(device,servidor)) - sum(avg(node_filesystem_free_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"xfs|ext.*\"})by(device,servidor))))",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  {
   "title": "Resource Details：【$servidor】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} / (node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} + 1)/ (node_memory_SwapTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mode=\"iowait\"}[$interval])) * 100"
    }
   ]
  },
  {
   "title": "Internet traffic per hour $servidor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\", mode='system'})"
    }
   ]
  },
  {
   "title": "Free inodes:$maxmount ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "【$servidor】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{servidor=~'$servidor',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {servidor=~'$servidor',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{servidor=~'$servidor',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{servidor=~'$servidor',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {servidor=~'$servidor',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{servidor=~'$servidor',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{servidor=~'$servidor',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Total filefd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mode=\"system\"}[$interval])) by (servidor) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mode=\"user\"}[$interval])) by (servidor) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mode=\"iowait\"}[$interval])) by (servidor) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",mode=\"idle\"}[$interval])) by (servidor))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} - node_memory_MemAvailable_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"} / (node_memory_MemTotal_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\", mode='system'}) by (cpu,instance)) by(servidor)",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "s", "label": "Time read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval]) / rate(node_disk_reads_completed_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "{{device}}_Read time"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval]) / rate(node_disk_writes_completed_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "graph",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "used filefd" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{tipo=~\"$tipo\",entorno=~\"$entorno\",servidor=~\"$servidor\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  }
 ]
}