{
 "title": "Recursos_Dockers (13946)",
 "description": "cAdvisor with node selection",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sum_without",
    "label": "sum",
    "query": "unsum,instance,image,container_label_restartcount,device"
   },
   {
    "name": "entorno",
    "label": "Ubicacion",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total, entorno)"
    }
   },
   {
    "name": "maquina",
    "label": "Maquina",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{entorno=\"$entorno\"}, maquina)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Maquina (s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lista de Nodos",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(container_last_seen{maquina=~\"$maquina\",image!=\"\"}) by (maquina)"
    },
    {
     "expr": "sum(machine_cpu_cores{maquina=~\"$maquina\"}) by (maquina)"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{maquina=~\"$maquina\",image!=\"\"}[5m]) * 100)by (maquina) / sum(machine_cpu_cores{maquina=~\"$maquina\"}) by (maquina)"
    },
    {
     "expr": "((sum(container_memory_usage_bytes{maquina=~\"$maquina\",image!=\"\"}) by (maquina) - sum(container_memory_cache{maquina=~\"$maquina\",image!=\"\"}) by (maquina)) / sum(machine_memory_bytes{maquina=~\"$maquina\"}) by (maquina)) * 100"
    },
    {
     "expr": "sum(container_memory_usage_bytes{maquina=~\"$maquina\",image!=\"\"}) by (maquina) - sum(container_memory_cache{maquina=~\"$maquina\",image!=\"\"}) by (maquina)"
    },
    {
     "expr": "sum(machine_memory_bytes{maquina=~\"$maquina\"}) by (maquina)"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{maquina=~\"$maquina\",image!=\"\"}[5m]))by (maquina)"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{maquina=~\"$maquina\",image!=\"\"}[5m]))by (maquina)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{maquina=~\"$maquina\",image!=\"\"}[5m]))by (maquina)"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{maquina=~\"$maquina\",image!=\"\"}[5m]))by (maquina)"
    }
   ]
  },
  {
   "title": "【$maquina】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage: Servidor $maquina",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_cpu_user_seconds_total{maquina=~\"$maquina\",image!=\"\"}[5m]) * 100)",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage: Servidor $maquina",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (container_memory_usage_bytes{maquina=~\"$maquina\",image!=\"\"} - container_memory_cache{maquina=~\"$maquina\",image!=\"\"})",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "I/O Tx: Servidor $maquina",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_fs_writes_bytes_total{maquina=~\"$maquina\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
     "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "I/O Rx: Servidor $maquina",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_fs_reads_bytes_total{maquina=~\"$maquina\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
     "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Network Tx: Servidor $maquina",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_network_transmit_bytes_total{maquina=~\"$maquina\",image!=\"\"}[5m]))",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Rx: Servidor $maquina",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_network_receive_bytes_total{maquina=~\"$maquina\",image!=\"\"}[5m]))",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  }
 ]
}