version: "3.3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/claudi/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
      
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - /home/claudi/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw

  web3:
    image: claclin73/ngnix:1.25.1
    container_name: web3
    restart: always
    expose:
      - "80"
    volumes:
      - /home/claudi/MANUALES/:/var/www/html/
      - /home/claudi/MANUALES/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=botclaudi.ddns.net
      - LETSENCRYPT_HOST=botclaudi.ddns.net
      - LETSENCRYPT_EMAIL=claclin73@gmail.com

  web4:
    image: claclin73/ngnix:1.25.1
    container_name: web4
    restart: always
    expose:
      - "80"
    volumes:
      - /home/claudi/MANUALES2/:/var/www/html/
      - /home/claudi/MANUALES2/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=conocimientos.ddns.net
      - LETSENCRYPT_HOST=conocimientos.ddns.net
      - LETSENCRYPT_EMAIL=oscarramiro73@gmail.com

  # Configuración de php-fpm
  php-fpm:
    image: php:8-fpm
    container_name: php
    restart: always
    volumes:
      - /home/claudi/MANUALES:/var/www/html
