version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/clau/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - /home/clau/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw
  www:
    image: claclin73/ngnix:1.25.1
    container_name: web
    restart: always
    expose:
      - "80"
    volumes:
      - /home/clau/HTML/index.html:/usr/share/nginx/html/index.html:ro
      - /home/clau/HTML/:/usr/share/nginx/html/
      - /home/clau/nginx/access.log:/var/log/nginx/logs/access.log
      - /home/clau/nginx/error.log:/var/log/nginx/logs/error.log
    environment:
      - VIRTUAL_HOST=botclaudi.ddns.net
      - LETSENCRYPT_HOST=botclaudi.ddns.net
      - LETSENCRYPT_EMAIL=claclin73@gmail.com
   
