version: "3.1"
services:
    db:
        image: mariadb
        container_name: mariadb
        restart: always
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ivrdb
            MYSQL_ROOT_PASSWORD: claudi 
        volumes:
             - /opt/Core/application_host/mariadb/persistent:/var/lib/mysql

