# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: claudi 
    volumes:
      - /home/clau/HTML/mariadb/persistent:/var/lib/mysql
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: phpadmin
    restart: always
    ports:
       - '8000:80'
    links:
        - mysql:mysql
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: hakase-labs123
        PMA_HOST: db
