# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"
services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: claudi 
    volumes:
      - /home/clau/HTML/mariadb/persistent:/var/lib/mysql

