# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"

# Servidor nginx
services:
  web:
    image: nginx:latest
    container_name: web2
    ports:
      - "8080:80"
      - "8321:80"
    volumes:
      - /home/clau/HTML:/var/www/html
      - /home/clau/HTML/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  # Configuración de php-fpm
  php-fpm:
    image: php:8-fpm
    container_name: php
    volumes:
      - /home/clau/HTML:/var/www/html
