version: '2.1'
services:
  ngnix:
    image: claclin73/ngnix:1.25.1
    container_name: web2
    restart: always
    ports:
      - "80:80"
      - "8321:80"
    environment:
      VIRTUAL_HOST: claudi.com
    volumes:
      - /home/clau/HTML/index.html:/usr/share/nginx/html/index.html:ro
      - /home/clau/HTML/:/usr/share/nginx/html/

  php:
    image: php:8.1.21RC1-fpm
    container_name: php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /home/clau/HTML/:/var/www/html
 
