# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"

# Servidor nginx
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "8321:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    image: claclin73/ngnix:1.25.1
    container_name: web2
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: claudi.com
    volumes:
      - /home/clau/HTML/:/var/www/html/
      - /home/clau/HTML/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  # Configuración de php-fpm
  php-fpm:
    image: php:8-fpm
    container_name: php
    volumes:
      - /home/clau/HTML:/var/www/html

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: claudi 
    volumes:
      - /home/clau/HTML/mariadb/persistent:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin
    links: 
      - db:db
    ports:
      - 3309:80
    environment:
      MYSQL_USERNAME: root
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: claudi
