version: '2.1'
networks:
    nginx-php74-mysql8-node:

services:

    # nginx
    nginx-service:
        image: claclin73/ngnix:1.25.1
        container_name: web2
        ports:
            - "8080:80"
            - "8321:80"
        volumes:
            - /home/clau/HTML/index.html:/usr/share/nginx/html/index.html:ro
            - /home/clau/HTML/:/usr/share/nginx/html/
            - /home/clau/HTML/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
        networks:
            - nginx-php74-mysql8-node

    # php
    php74-service:
        image: php:8.1.21RC1-fpm
        container_name: php
        ports:
            - "9000:9000"
        volumes:
            - /home/clau/HTML:/var/www/project
        networks:
            - nginx-php74-mysql8-node

